# runs tests for push-events, for pull requests and using cron schedule:
name: Regression Test
on:
  push:
    # runs tests for commits pushed to master
    branches:
      - main
    # run tests for GitHub Pull requests. Test result is visible in the Pull Request page.
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          uses: joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: /tests
            ROBOT_REPORTS_DIR: /reports
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: /reports
