# runs tests for push-events, for pull requests and using cron schedule:
name: Regression Test
on:
  push:
    # runs tests for commits pushed to master
    branches:
      - main
    # run tests for GitHub Pull requests. Test result is visible in the Pull Request page.
jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:

        - uses: actions/checkout@v2

        - name: Create folder for reports
          run: mkdir Reports

        - name: Run Robot Framework Tests

          run: |
            docker run \
                -v $PWD/reports:/opt/robotframework/reports:Z \
                -v $PWD/tests:/opt/robotframework/tests:Z \
                -e BROWSER=chrome \
                ppodgorsek/robot-framework:latest
